return {
    ["Accent Color"] = "主菜单颜色",
    ["Config"] = "配置文件名",
    ["Configs List"] = "配置列表",
    ["Copy Force Config"] = "复制强制配置",
    ["Create"] = "创建",
    ["Hide Watermark"] = "隐藏水印",
    ["Maximum of Servers"] = "服务器数量上限",
    ["Menu Keybind"] = "菜单开关快捷键",
    ["Reduced Motion"] = "减少动画效果",
    ["Reset UI Setting"] = "重置菜单设置",
    ["Reset/Delete Workspace"] = "重置/删除所有配置文件",
    ["Search Server"] = "搜索服务器",
    ["Select Language"] = "选择语言",
    ["Server Refresh Delay"] = "服务器刷新延迟",
    ["Show Tab Infomation"] = "显示标签页信息",
    ["Start Find Server"] = "开始搜索服务器",
    ["UI Size"] = "菜单大小",
    ["Unload Script"] = "卸载脚本",

    ["Hop Server (New Server)"] = "跳转到新服务器",
    ["Hop Server (Old Server)"] = "跳转到旧服务器",
    ["Rejoin Server"] = "重新加入服务器",
    ["JobId"] = "服务器ID",
    ["Join Server JobId"] = "通过ID加入服务器",
    ["Copy JobId"] = "复制服务器ID",
}
