return {
    ["Accent Color"] = "强调色",
    ["Config"] = "配置",
    ["Configs List"] = "配置列表",
    ["Copy Force Config"] = "复制强制配置",
    ["Create"] = "创建",
    ["Hide Watermark"] = "隐藏水印",
    ["Maximum of Servers"] = "最大服务器数",
    ["Menu Keybind"] = "菜单快捷键",
    ["Reduced Motion"] = "减少动画效果",
    ["Reset UI Setting"] = "重置界面设置",
    ["Reset/Delete Workspace"] = "重置/删除工作区",
    ["Search Server"] = "搜索服务器",
    ["Select Language"] = "选择语言",
    ["Server Refresh Delay"] = "服务器刷新间隔",
    ["Show Tab Infomation"] = "显示选项卡信息",
    ["Start Find Server"] = "开始搜索服务器",
    ["UI Size"] = "界面大小",
    ["Unload Script"] = "卸载脚本",

    ["Hop Server (New Server)"] = "切换至新服务器",
    ["Hop Server (Old Server)"] = "切换至旧服务器",
    ["Rejoin Server"] = "重新加入服务器",
    ["JobId"] = "服务器ID",
    ["Join Server JobId"] = "通过ID加入服务器",
    ["Copy JobId"] = "复制服务器ID",
}
