return {
    ["Accent Color"] = "Warna Aksen",
    ["Config"] = "Konfigurasi",
    ["Configs List"] = "Daftar Konfigurasi",
    ["Copy Force Config"] = "Salin Paksa Konfigurasi",
    ["Create"] = "Peti",
    ["Hide Watermark"] = "Sembunyikan Watermark",
    ["Maximum of Servers"] = "Server Maksimal",
    ["Menu Keybind"] = "Menu Tombol Pintasan",
    ["Reduced Motion"] = "Mengurangi Gerakan",
    ["Reset UI Setting"] = "Mengatur Ulang Pengaturan UI",
    ["Reset/Delete Workspace"] = "Mengatur Ulang/Menghapus Workspace",
    ["Search Server"] = "Cari Server",
    ["Select Language"] = "Pilih Bahasa",
    ["Server Refresh Delay"] = "Jeda Refresh Server",
    ["Show Tab Infomation"] = "Perlihatkan Informasi Tab",
    ["Start Find Server"] = "Mulai Mencari Server",
    ["UI Size"] = "Ukuran UI",
    ["Unload Script"] = "Melepas Script",
    
    ["Hop Server (New Server)"] = "Pindah Server (Server Baru)",
    ["Hop Server (Old Server)"] = "Pindah Server (Server Lama)",
    ["Rejoin Server"] = "Bergabung Kembali pada Server",
    ["JobId"] = "JobId",
    ["Join Server JobId"] = "Bergabung ke Server JobId",
    ["Copy JobId"] = "Salin JobId",
}
