return {
    ["Accent Color"] = "Colore Accento",
    ["Config"] = "Configurazione",
    ["Configs List"] = "Lista Di Config",
    ["Copy Force Config"] = "Copia Forzata Config",
    ["Create"] = "Crea",
    ["Hide Watermark"] = "Nascondi Watermark",
    ["Maximum of Servers"] = "Server Massimi",
    ["Menu Keybind"] = "Keybind Menu",
    ["Reduced Motion"] = "Movimento Ridotto",
    ["Reset UI Setting"] = "Reset Impostazioni UI",
    ["Reset/Delete Workspace"] = "Elimina Workspace",
    ["Search Server"] = "Cerca Server",
    ["Select Language"] = "Seleziona Lingua",
    ["Server Refresh Delay"] = "Ritardo Refresh Server",
    ["Show Tab Infomation"] = "Mostra Tabella Informazioni",
    ["Start Find Server"] = "Inizia A Cercare Server",
    ["UI Size"] = "Dimensione UI",
    ["Unload Script"] = "Annulla Script",
    
    ["Hop Server (New Server)"] = "Vai Nel Server (Nuovo Server)",
    ["Hop Server (Old Server)"] = "Vai Nel Server (Vecchio Server)",
    ["Rejoin Server"] = "Riunisciti Al Server",
    ["JobId"] = "JobId",
    ["Join Server JobId"] = "Unisciti Al Server JobId",
    ["Copy JobId"] = "Copia JobId",
    
    ["Enable Background"] = "Abilita Background",
    ["Background URL"] = "URL Del Background",
}
