return {
    ["Accent Color"] = "Цвет акцента",
    ["Config"] = "Конфиг",
    ["Configs List"] = "Список конфигов",
    ["Copy Force Config"] = "Копировать принудительный конфиг",
    ["Create"] = "Создать",
    ["Hide Watermark"] = "Скрыть водяной знак",
    ["Maximum of Servers"] = "Максимум серверов",
    ["Menu Keybind"] = "Клавиша меню",
    ["Reduced Motion"] = "Уменьшение движения",
    ["Reset UI Setting"] = "Сбросить настройки UI",
    ["Reset/Delete Workspace"] = "Сбросить/Удалить воркспейс скрипта",
    ["Search Server"] = "Поиск сервера",
    ["Select Language"] = "Выбрать язык",
    ["Server Refresh Delay"] = "Задержка обновления серверов",
    ["Show Tab Infomation"] = "Показать информацию о вкладке",
    ["Start Find Server"] = "Начать поиск сервера",
    ["UI Size"] = "Размер UI",
    ["Unload Script"] = "Выгрузить скрипт",
    
    ["Hop Server (New Server)"] = "Перейти на сервер (новый)",
    ["Hop Server (Old Server)"] = "Перейти на сервер (старый)",
    ["Rejoin Server"] = "Перезайти на сервер",
    ["JobId"] = "JobId",
    ["Join Server JobId"] = "Присоединиться по JobId",
    ["Copy JobId"] = "Копировать JobId",
}