return {
    ["Accent Color"] = "Color de Acento",
    ["Config"] = "Configuración",
    ["Configs List"] = "Lista de Configuraciones",
    ["Copy Force Config"] = "Copiar Configuración Forzada",
    ["Create"] = "Crear",
    ["Hide Watermark"] = "Ocultar Marca de Agua",
    ["Maximum of Servers"] = "Máximo de Servidores",
    ["Menu Keybind"] = "Tecla del Menú",
    ["Reduced Motion"] = "Reducir Movimiento",
    ["Reset UI Setting"] = "Resetear Ajustes de UI",
    ["Reset/Delete Workspace"] = "Borrar Workspace",
    ["Search Server"] = "Buscar Servidor",
    ["Select Language"] = "Seleccionar Idioma",
    ["Server Refresh Delay"] = "Retraso de Recarga de Servidor",
    ["Show Tab Infomation"] = "Mostrar Información",
    ["Start Find Server"] = "Buscar Servidor",
    ["UI Size"] = "Tamaño de la UI",
    ["Unload Script"] = "Cerrar Script",

    ["Hop Server (New Server)"] = "Unirse a Servidor (Nuevo)",
    ["Hop Server (Old Server)"] = "Unirse a Servidor (Antiguo)",
    ["Rejoin Server"] = "Reconectarse al Servidor",
    ["JobId"] = "JobId",
    ["Join Server JobId"] = "Unirse al JobId de Servidor",
    ["Copy JobId"] = "Copiar JobId",
}
