return {
    ["Accent Color"] = "สี UI หลัก",
    ["Configs List"] = "รายการการตั้งค่า",
    ["Copy Force Config"] = "คัดลอกการตั้งค่าบังคับ",
    ["Create"] = "สร้าง",
    ["Hide Watermark"] = "ซ่อนลายน้ำ",
    ["Maximum of Servers"] = "จำนวนเซิร์ฟเวอร์สูงสุด",
    ["Menu Keybind"] = "Menu Keybind",
    ["Reduced Motion"] = "ลดแอนิเมชั่น",
    ["Reset UI Setting"] = "รีเซ็ตการตั้งค่า UI",
    ["Reset/Delete Workspace"] = "รีเซ็ต/ลบ Workspace",
    ["Search Server"] = "ค้นหาเซิร์ฟเวอร์",
    ["Select Language"] = "เลือกภาษา",
    ["Server Refresh Delay"] = "ดีเลย์ในการรีเฟรชเซิร์ฟเวอร์",
    ["Show Tab Infomation"] = "แสดงข้อมูลแท็บ",
    ["Start Find Server"] = "เริ่มค้นหาเซิร์ฟเวอร์",
    ["UI Size"] = "ขนาด UI",
    ["Unload Script"] = "ยกเลิกการโหลดสคริปต์",
}
