return {
    ["Accent Color"] = "สีเมนูหลัก",
    ["Config"] = "ชื่อไฟล์ตั้งค่า",
    ["Configs List"] = "รายการการตั้งค่า",
    ["Copy Force Config"] = "คัดลอกการตั้งค่าบังคับ",
    ["Create"] = "สร้าง",
    ["Hide Watermark"] = "ซ่อนลายน้ำ",
    ["Maximum of Servers"] = "จำนวนเซิร์ฟเวอร์สูงสุด",
    ["Menu Keybind"] = "คีย์ลัดเปิดปิดเมนู",
    ["Reduced Motion"] = "ลดแอนิเมชั่น",
    ["Reset UI Setting"] = "รีเซ็ตการตั้งค่าเมนู",
    ["Reset/Delete Workspace"] = "รีเซ็ต/ลบ ไฟล์ตั้งค่าทั้งหมด",
    ["Search Server"] = "ค้นหาเซิร์ฟเวอร์",
    ["Select Language"] = "เลือกภาษา",
    ["Server Refresh Delay"] = "ดีเลย์ในการรีเฟรชเซิร์ฟเวอร์",
    ["Show Tab Infomation"] = "แสดงข้อมูลแท็บ",
    ["Start Find Server"] = "เริ่มค้นหาเซิร์ฟเวอร์",
    ["UI Size"] = "ขนาดเมนู",
    ["Unload Script"] = "ยกเลิกการโหลดสคริปต์",
    
    ["Hop Server (New Server)"] = "ย้ายไปเซิฟใหม่",
    ["Hop Server (Old Server)"] = "ย้ายไปเซิฟเก่า",
    ["Rejoin Server"] = "ออกเกมเข้าใหม่",
    ["JobId"] = "ไอดีเซิฟเวอร์",
    ["Join Server JobId"] = "เข้าร่วมเซิฟเวอร์ด้วยไอดี",
    ["Copy JobId"] = "คัดลอกไอดีเซิฟเวอร์",
}
